### PR TITLE
core: remove the shared state from the tests

### LINKED ISSUE #33: Better test isolation
Currentlym, most tests will fail unpredictably when run with more than one test-thread (which is the default). This is because the cgroup creation / destruction uses shared state. Since the state exists within cgroup-namespaces, we might override the cgroup path on a per-test basis. We already have separate cgroup names for each hypervisor instance.

This would isolate the tests from each other and hopefully make it possible to execute them in parallel.

```plain
running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/main.rs (target/debug/deps/hello_part-a72744c423b3fe3f)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target/debug/deps/linux_apex_core-a78532244570a6d6)

running 9 tests
test cgroup::tests::import_root ... ok
test cgroup::tests::mv ... FAILED
test cgroup::tests::new_root ... FAILED
test cgroup::tests::get_pids ... FAILED
test cgroup::tests::is_cgroup ... ok
test cgroup::tests::frozen ... ok
test cgroup::tests::kill ... FAILED
test cgroup::tests::populated ... FAILED
test cgroup::tests::new ... FAILED

failures:

---- cgroup::tests::mv stdout ----
thread 'cgroup::tests::mv' panicked at 'called `Result::unwrap()` on an `Err` value: ENOENT: No such file or directory', core/src/cgroup.rs:312:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- cgroup::tests::new_root stdout ----
thread 'cgroup::tests::new_root' panicked at 'called `Result::unwrap()` on an `Err` value: Device or resource busy (os error 16)', core/src/cgroup.rs:271:17

---- cgroup::tests::get_pids stdout ----
thread 'cgroup::tests::get_pids' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)', core/src/cgroup.rs:335:32

---- cgroup::tests::kill stdout ----
thread 'cgroup::tests::kill' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)', core/src/cgroup.rs:410:17

---- cgroup::tests::populated stdout ----
thread 'cgroup::tests::populated' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)', core/src/cgroup.rs:366:17

---- cgroup::tests::new stdout ----
thread 'cgroup::tests::new' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)', core/src/cgroup.rs:300:18


failures:
    cgroup::tests::get_pids
    cgroup::tests::kill
    cgroup::tests::mv
    cgroup::tests::new
    cgroup::tests::new_root
    cgroup::tests::populated

test result: FAILED. 3 passed; 6 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s
```

### PR DESCRIPTION
**Pull request by emilengler**
This commit removes the shared state from the cgroup tests, by generating a unique random name for each and every cgroup.

Fixes #33

### CODE REVIEW

File: core/src/cgroup.rs [hunk 1]
```diff
@@ -432,4 +436,10 @@ mod tests {
             .unwrap()
             .join(super::current_cgroup().unwrap())
     }
+
+    /// Generates a name for the current cgroup
+    fn gen_name() -> String {
+        let val: u64 = rand::random();
```
Comment (dadada) [inline core/src/cgroup.rs:442]: Please use something that is reliably unique instead (e.g., a UUID). Or just the thread ID (`gettid`) of the test.

**Review by dadada — CHANGES_REQUESTED** [review]
.

File: core/src/cgroup.rs (hunk 1 above)
Comment (wucke13) [reply core/src/cgroup.rs:442]: +1 for uuid. https://docs.rs/uuid/latest/uuid/ looks good at a first glance

Comment (emilengler) [reply core/src/cgroup.rs:442]: I personally think that the UUID crate is overkill for a test dependency. 64-bit integers are totally sufficient in that case. I've added a loop on top of it, in order to avoid collisions, although the probability is with $2^{-64}$ very very low.

Comment (emilengler) [reply core/src/cgroup.rs]: Beside this, the UUID crate seems to require an instance before you can generate UUIDs. This would already make the code less obvious in my opinion, compared to the anonymous integer generator.

**Review by Steav005 — APPROVED** [review]
