### PR TITLE
fix panic on empty read from file

### LINKED ISSUE #16: Panic when reading from a Sampling port destination
I have a partition that runs a process that very frequently reads from a sampling port. After running the partition for some time, I reliably get a read from an empty file, which causes a panic. The panic is fixed in #15, but the error persists. This is from the execution of the partition (Echo) with the fix from #15 applied. Now it panics in apex-rs?

```
 ERROR Partition: Echo                              > PanicInfo {
 ERROR Partition: Echo                              >     payload: Any { .. },
 ERROR Partition: Echo                              >     message: Some(
 ERROR Partition: Echo                              >         called `Result::unwrap()` on an `Err` value: TypedError { err: Panic, source: failed to fill whole buffer
 ERROR Partition: Echo                              >
 ERROR Partition: Echo                              >         Stack backtrace:
 ERROR Partition: Echo                              >            0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
 ERROR Partition: Echo                              >            1: linux_apex_core::file::TempFile<T>::read
 ERROR Partition: Echo                              >            2: <S as apex_rs::apex::sampling::abstraction::ApexSamplingPortP4Ext>::sampling_port_receive_unchecked
 ERROR Partition: Echo                              >            3: <apex_rs::apex::sampling::abstraction::SamplingPortDestination<_,H> as echo::echo::RunableProcess>::run_process
 ERROR Partition: Echo                              >            4: echo::entry_point_aperiodic
 ERROR Partition: Echo                              >            5: apex_rs_linux::process::Process::start::{{closure}} },
 ERROR Partition: Echo                              >     ),
 ERROR Partition: Echo                              >     location: Location {
 ERROR Partition: Echo                              >         file: "/home/dadada/.cargo/git/checkouts/apex-linux-53d7a06a5cb9e565/cdc4225/partition/src/apex.rs",
 ERROR Partition: Echo                              >         line: 157,
 ERROR Partition: Echo                              >         col: 14,
 ERROR Partition: Echo                              >     },
 ERROR Partition: Echo                              >     can_unwind: true,
 ERROR Partition: Echo                              > }

```

### PR DESCRIPTION
**Pull request by dadada**
This fixes #16 a read from an empty file or from the end of a file. I'm not entirely sure under which conditions the file can be empty, but the cursor might be moved between seeking it to the beginnging of the file and reading from it. I encountered the problem only occasionally when running the hypervisor with two partitions for a while.

### CODE REVIEW

**Comment by dadada** [comment]
Sorry for all the force pushes. Should be fine now.

**Comment by dadada** [comment]
This does not work, since the `Vec` does not have any elements.

**Review by wucke13 — APPROVED** [review]

File: partition/src/apex.rs [hunk 1]
```diff
@@ -152,11 +152,12 @@ impl ApexSamplingPortP4 for ApexLinuxPartition {
...
-            .read()
-            .unwrap()
-            .get(sampling_port_id as usize - 1)
-        {
+        let read = if let Ok(read) = SAMPLING_PORTS.read() {
+            read
+        } else {
+            return Err(ErrorReturnCode::NotAvailable);
+        };
+        if let Some((port, val)) = read.get(sampling_port_id as usize - 1) {
```
Comment (emilengler) [inline partition/src/apex.rs:160]: Can `sampling_port_id` be zero? I see potential for an unsigned integer wrap here. If not, I would comment it at least.

Comment (dadada) [reply partition/src/apex.rs:160]: The `sampling_port_id` is always greater than zero, since it is (incidentally) derived from the current length, after inserting an element, of the `ArrayVec` storing the sampling ports. https://github.com/aeronautical-informatics/apex-linux/pull/15/files#diff-d21de3347b5e6174c93c455b533568b798d139a47f7ba2564655c0731e27f889R120
